version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always
